name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: sudo apt install iverilog verilator yosys
      - name: Compile with Verilator
        run: make verilate
      # Yosys 0.9 does not support features we use, so it is disabled for now.
      #- name: Synthesize with yosys
      #  run: make yosys
      - name: Run with Icarus Verilog
        run: make run +count=1000
